# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WwwGo < Formula
  desc "Serve simple static file server"
  homepage "https://github.com/linzhengen/www-go"
  version "0.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/linzhengen/www-go/releases/download/v0.1.1/www-go_0.1.1_darwin_amd64.tar.gz"
      sha256 "8f80f492816163f87ca370aee08b4a5db657f639dec280b393e4e777fb3bcd59"
    end
    if Hardware::CPU.arm?
      url "https://github.com/linzhengen/www-go/releases/download/v0.1.1/www-go_0.1.1_darwin_arm64.tar.gz"
      sha256 "fa847698a836f031ff57d3d6d2ed02202949b7a9bd32a76940d27ddd46fcda86"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/linzhengen/www-go/releases/download/v0.1.1/www-go_0.1.1_linux_amd64.tar.gz"
      sha256 "1b0e2f725bdaec4be8261b28a2d84028498e2dbbdd2d2d7888d136f6918ea166"
    end
    if Hardware::CPU.arm?
      url "https://github.com/linzhengen/www-go/releases/download/v0.1.1/www-go_0.1.1_linux_arm64.tar.gz"
      sha256 "556acac877cd8c49d9b4d1f45614561790393184272105eddc65a81fa9e78e65"
    end
  end

  head "https://github.com/linzhengen/www-go/releases/download/v0.1.1/www-go_0.1.1_darwin_amd64.tar.gz"

  def install
    bin.install "www-go"
  end
end