# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WwwGo < Formula
  desc "Serve simple static file server"
  homepage "https://github.com/linzhengen/www-go"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/linzhengen/www-go/releases/download/v0.1.0/www-go_darwin_amd64"
      sha256 "60cce877fe15e5d91c8940b839f746bc02d520728daaa7f31264ba52a3be0125"
    end
    if Hardware::CPU.arm?
      url "https://github.com/linzhengen/www-go/releases/download/v0.1.0/www-go_darwin_arm64"
      sha256 "744f39822588314fee63faa4285e4a5d6bb7573f1cad5aaefe19fb2f52f3af83"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/linzhengen/www-go/releases/download/v0.1.0/www-go_linux_amd64"
      sha256 "83a0c117b38915f1f5b7603299c051fef46628cadf7f3ebcf999ae8848e4f871"
    end
    if Hardware::CPU.arm?
      url "https://github.com/weaveworks/eksctl/releases/download/v0.67.0/go_linux_arm64"
      sha256 "6400e05804645b7c4f78a83ec3a394c096cdf8f465c06154e468b165c258abf4"
    end
  end

  head "https://github.com/linzhengen/www-go/releases/download/latest_release/www-go_darwin_amd64"

  def install
    bin.install "www-go"
  end
end